config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :user, only: [:edit, :update]

  get "section_fields", to: "admin#section_fields"

  localized do
    get  :login,   to: "sessions#new"
    post :session, to: "sessions#create"
    get  :logout,  to: "sessions#destroy"

    resources :visual_works
    resources :action_works

    resources :works, only: [] do
      collection do
        get :admin
      end
    end

    # Tags
    resources :tags, except: [:new, :edit] do
      get "admin", on: :collection
    end

    get "contact", to: "contact_messages#new"
    resources :contact_messages, only: [:create]

    get "about", to: "dashboards#about"

    root to: "dashboards#front"
    get "more_works", to: "dashboards#more_works"
  end

  get "/", to: "dashboards#front"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_locale,
                :set_tags

  before_action do
    ActiveStorage::Current.url_options = { host: request.host }
  end

  around_action :set_locale_from_url
  helper_method :current_user, :current_user?

  private

  def set_locale
    locale = params[:locale]

    return if locale && I18n.available_locales.map(&:to_s).include?(locale)

    location = request.fullpath

    redirect_to "/#{locale_from_headers}#{location}"
  end

  def set_tags
    @enabled_tags = Tag.enabled.includes(:plain_text_translations)
  end

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find(session[:user_id])
  end

  def current_user?
    !!current_user
  end

  def locale_from_headers
    return I18n.default_locale unless (header = request.headers["HTTP_ACCEPT_LANGUAGE"])

    AcceptLanguage
      .parse(header)
      .match(*I18n.available_locales) || I18n.default_locale
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def title(title = nil)
    title += " | " unless title.nil?
    content_for(:title) { title }
  end

  def page_title(title)
    strip_tags(title).then(&method(:title))

    content_for(:page_title) { content_tag(:h1, title.html_safe, id: "main_title") } # rubocop:disable Rails/OutputSafety
  end

  def site_name
    tag = front? ? :h1 : :span
    img_src = front? ? "MireiaZantop.png" : "MZ.png"
    title = front? ? nil : t("home")

    content_tag(
      tag,
      link_to_unless_current(
        image_tag(
          img_src,
          alt: "Mireia Zantop"
        ),
        root_path,
        title:
      ),
      id: "site_name"
    )
  end

  def body_classes
    classes = [controller.controller_name, controller.action_name]
    classes << "with-sidebar" if sidebar?
    classes << "no-front" unless front?

    classes.join(" ")
  end

  def front?
    controller.controller_name == "dashboards" && controller.action_name == "front"
  end

  def active_link?(url)
    return "active" if url == request.fullpath
  end

  def page_name
    case controller.controller_name
    when "action_works"
      t("menu.action_art")
    when "visual_works"
      t("menu.visual_art")
    when "dashboards"
      t("menu.about") if controller.action_name == "about"
    when "contact_messages"
      t("menu.contact")
    end
  end

  def view_more(destination)
    content_tag "p", link_to(raw("#{t('view_more')} &rarr;"), destination), class: "view-more"
  end

  private

  def sidebar?
    (!front? && %w[new edit admin].exclude?(controller.action_name)) ||
      controller.controller_name == "contact_messages"
  end
end

app/views/application/_admin_bar.html.erb
<div id="admin-bar">
  <div class="container">
    <div id="generic-controls">
      <%= link_to "Crear treball d'acció", new_action_work_path, class: "btn" %>
      <%= link_to "Crear treball visual",  new_visual_work_path, class: "btn" %>
      <%= link_to "Ordenar treballs",      admin_works_path,     class: "btn" %>
      <%= link_to "Administrar tags",      admin_tags_path,      class: "btn" %>
    </div>
    <div id='session-controls'>
      <%= link_to t('change_password'), edit_user_path, class: "btn" %>
      <%= link_to 'Sortir', logout_path, class: "logout btn" %>
    </div>
    <% if content_for(:admin_bar_second_row) %>
      <div class="break"></div>
      <div id="admin-bar_second-row">
        <%= yield :admin_bar_second_row %>
      </div>
    <% end %>
  </div>
</div>

app/views/application/_flash_messages.html.erb
<div id="flash-messages">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/application/_footer.html.erb
<footer id="footer" role="contentinfo">
  <div class='container'>
    <div id="footer_page_name">
      <h3><%= link_to 'MireiaZantop.com', root_path %></h3>
    </div>
    <div id="footer_menu">
      <%= link_to t('menu.action_art'), action_works_path %>
      <%= link_to t('menu.visual_art'), visual_works_path %>
      <%= link_to t('menu.about'), about_path %>
      <%= link_to t('menu.contact'), contact_path %>
    </div>
  </div>
</footer>

app/views/application/_header.html.erb
<header role="banner">
  <div class="container header-container">
    <div id="brand">
      <%= site_name %>
    </div>
    <%= render 'menu' %>
    <ul id="select-lang">
      <%= lang_selector.html_safe %>
    </ul>
  </div>
</header>

app/views/application/_image_fields.html.erb
<div class="fields">
  <%= form.simple_fields_for "image_attributes[]", image do |fields| %>
    <div class="sorting-controls">
      <a href="javascript:void(0)" data-behaviour="move-up">⬆️</a>
      <a href="javascript:void(0)" data-behaviour="move-down">⬇️</a>
    </div>

    <%= fields.input :image %>
    <%= fields.input :video %>
    <%= fields.input :credits, as: :rich_text_area %>
    <%= fields.input :position,
                     as: :hidden,
                     input_html: { data: { attribute: "position" } } %>
    <%= fields.input :_destroy,
                     as: :hidden,
                     input_html: { data: { attribute: "_destroy" } } %>
    <%= button_tag "Esborrar imatge",
                   type: :button,
                   class: "push-right btn btn-danger btn-smaller",
                   data: { behaviour: "remove-record" } %>
  <% end %>
</div>

app/views/application/_menu.html.erb
<nav id="main_menu" role="navigation">
  <% if front? %>
    <i>Art</i>
    <div class="menu-item">
      <%= link_to t('action'), action_works_path, class: 'action' %>
    </div>
    <div class="menu-item">
      <%= link_to t('visual'), visual_works_path, class: 'visual' %>
    </div>
  <% else %>
    <%= link_to t('menu.action_art'), action_works_path, class: active_link?(action_works_path) %>
    <%= link_to t('menu.visual_art'), visual_works_path, class: active_link?(visual_works_path) %>
    <%= link_to t('menu.about'), about_path, class: active_link?(about_path) %>
    <%= link_to t('menu.contact'), contact_path, class: active_link?(contact_path)%>
  <% end %>
</nav>

app/views/application/_section_fields.html.erb
<div class="fields" data-new-record=<%= section.new_record? %>>
  <%= form.simple_fields_for "section_attributes[]", section do |fields| %>
    <div class="sorting-controls">
      <a href="javascript:void(0)" data-behaviour="move-up">⬆️</a>
      <a href="javascript:void(0)" data-behaviour="move-down">⬇️</a>
    </div>

    <%= fields.input :title %>
    <%= fields.input :body, as: :rich_text_area %>
    <%= fields.input :position,
                     as: :hidden,
                     input_html: { data: { attribute: "position" } } %>
    <%= fields.input :_destroy,
                     as: :hidden,
                     input_html: { data: { attribute: "_destroy" } } %>
    <%= button_tag "Esborrar secció",
                   type: :button,
                   class: "push-right btn btn-danger btn-smaller",
                   data: { behaviour: "remove-record" } %>
  <% end %>
</div>

app/views/application/_sidebar.html.erb
<div id="sidebar">
  <%= yield :sidebar %>
  <div class="sidebar-block">
    <h2><%= t('categories') %></h2>
    <ul class="tags_list vertical-list">
      <% @enabled_tags.sort { |a, b| a.name <=> b.name }.each do |tag| %>
        <li>
          <%= link_to tag.name.humanize, tag_path(tag),
            class: active_link?(tag_url(tag, only_path: true)) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/application/work.html.erb
<% cache [locale, :show, work] do %>
  <%= page_title work.title %>
  <%= print_work_place work %>
  <%= print_work_date work %>
  <% if !work.images.empty? %>
    <div id="galleria" style="height: 500px">
      <% work.images.each do |image| %>
        <% if image.image? %>
          <%= link_to image_tag(image.image.thumb.to_s, data: { title: image.credits }),
            image.image.to_s %>
          <% end %>
        <% if image.video? %>
          <%= link_to content_tag(:span, "Watch this video", class: "video",
                                  data: {title: image.credits }),
            image.video %>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <%= print_work_techniques work %>
  <%= print_work_dimensions work %>
  <%= print_work_description work %>
  <%= print_work_tags work %>
<% end %>